name: BatDroppings
main: net.loadingchunks.plugins.BatDroppings.BatDroppings.BatDroppings
version: 0.1

commands:
   bd:
      description: Gets and Sets money drops
      usage: /bd <mob> <value>
