name: BatDroppings
main: net.loadingchunks.plugins.BatDroppings.BatDroppings.BatDroppings
version: 0.1

commands:
   bm:
      description: Gets and Sets money drops
      usage: /bm <mob> <value>
