name: BatDroppings
main: net.loadingchunks.plugins.BatDroppings.BatDroppings.BatDroppings
version: 0.1

commands:
   bd:
      description: Modifies money drops and reloads config.
      usage: 
        -  /bd set <mob> <value>
        -  /bd reload
